import { AVATAR_COLORS } from './constants'

const STAFF = [
  {
    id: 'stf_yunusa',
    name: 'Dr. Yunusa Muhammad Garba',
    email: 'ygarbawala@gmail.com',
    education: 'Human Anatomy',
    staffCode: 'Director',
    department: 'Executive Office',
    role: 'Managing Director / CEO',
    specialization: 'Reports to Board / Shareholders',
  },
  {
    id: 'stf_cbpo',
    name: 'Mr. Mohammed Abdulhamid Hassan',
    email: '',
    staffCode: 'Senior Manager',
    department: 'BD & Project Delivery',
    role: 'CBPO',
    specialization: 'Reports to MD / CEO',
  },
  {
    id: 'stf_cfo',
    name: 'Mr. Faisal Barda',
    email: '',
    staffCode: 'Manager',
    department: 'Finance & Accounts',
    role: 'CFO',
    specialization: 'Reports to MD / CEO; Board oversight',
  },
  {
    id: 'stf_kamba',
    name: 'Mr. Abubakar Abdullahi Kamba',
    email: 'abdullahikambaa@gmail.com',
    education: 'B.URP, Risk Management (M.Sc), MBA, PhD Corporate Governance & Leadership',
    specialization: 'Risk Management & Corporate Governance · Reports to MD / CEO',
    staffCode: 'Manager',
    department: 'Risk & Compliance',
    role: 'CRO',
    phone: '+234 806 945 1598',
  },
  {
    id: 'stf_abdulwaheed',
    name: 'Mr. Abdulwaheed Hassan',
    email: 'hassanabdulwaheed4@gmail.com',
    education: 'International Affairs Abd Diplomacy (M.Sc)',
    specialization: 'Administration · Reports to MD / CEO',
    staffCode: 'Manager',
    department: 'Corporate Services',
    role: 'CCSO',
    years: 9,
    phone: '+234 903 099 7659',
  },
  {
    id: 'stf_chikaire',
    name: 'Dr. Abdurrahman Umar Chikaire',
    email: 'drchikaire@gmail.com',
    education: 'MBBS, MPH, MBA',
    staffCode: 'Manager',
    role: 'CAO',
    department: 'Administration',
    specialization: 'Reports to MD / CEO',
    years: 10,
  },
  {
    id: 'stf_zulkarnaini',
    name: 'Mr Zulkarnaini Musa',
    email: 'naini5004@gmail.com',
    education: 'Electrical and Electronic Engineering (B.Sc)',
    specialization: 'PMO / Programme Coordination · Reports to CBPO',
    staffCode: 'Deputy Manager',
    department: 'BD & Project Delivery',
    role: 'Head, PMO / Programme Coordination',
    years: 8,
    phone: '+234 803 387 4843',
  },
  {
    id: 'stf_abdulkadir',
    name: 'Mr. Abdulkadir Abubakar',
    email: 'aq.qadeer198@gmail.com',
    education: 'Development Economin (M.Sc)',
    specialization: 'Procurement & logistics · Reports to CAO; project line to CBPO',
    staffCode: 'Assistant Manager',
    department: 'Logistics & Procurement',
    role: 'Head of Procurement / logistics coordination',
    years: 6,
    phone: '+234 903 683 5394',
  },
  {
    id: 'stf_ali_balaya',
    name: 'Mr. Ali Babayo',
    email: 'babayoali@gmail.com',
    staffCode: 'SBO',
    department: 'BD & Project Delivery',
    role: 'Project Management Officer — Ease',
    specialization: 'Reports to CBPO',
    birthday: '01-23',
    phone: '+234 806 575 8518',
  },
  {
    id: 'stf_mele',
    name: 'Mr. Abdulrahman Isa Mele',
    email: 'isameleabdulrahman@gmail.com',
    education: 'Criminology (B.Sc)',
    staffCode: 'BO',
    department: 'BD & Project Delivery',
    role: 'Reduce Project Lead',
    specialization: 'Reports to CBPO',
    years: 3,
  },
  {
    id: 'stf_abdulaziz',
    name: 'Mr. Abdulaziz Kabir',
    email: 'milmildydx@gmail.com',
    professional: 'Business Developer',
    staffCode: 'BO',
    specialization: 'Product Lead · Reports to CBPO',
    department: 'BD & Project Delivery',
    role: 'Product Lead',
    years: 7,
  },
  {
    id: 'stf_favor',
    name: 'Ms. Favor Patience Solomon',
    email: '',
    staffCode: 'BO',
    department: 'Legal & Company Secretariat',
    role: 'Legal Counsel (external)',
    specialization: 'Reports to MD / CEO; CBPO coordination',
  },
  {
    id: 'stf_hannah',
    name: 'Miss Hannah Rowland Ibimendi',
    email: 'hannahbella.rh@gmail.com',
    professional: 'Virtual Assistant (VA)',
    education: 'English and Literary Studies (B.A)',
    specialization: 'Secretarial and Office Management · Reports to MD / CEO',
    staffCode: 'ABO',
    department: 'Executive Office',
    role: 'Executive Assistant / Secretary to MD',
    years: 3,
    phone: '+234 905 910 0827',
    birthday: '06-13',
  },
  {
    id: 'stf_walid',
    name: 'Mr. Muhammad Abdullahi Walid',
    email: 'muhammadabdullahiwalid@yahoo.com',
    professional: 'Geounformation Society Of Nigeria',
    education: 'Remote Sensing and GIS (M.Sc)',
    specialization: 'Geospatial Analytics · Reports to CTPO / CFO / CBPO',
    staffCode: 'ABO',
    department: 'Administration',
    role: 'Basic integrations & service provision',
    years: 5,
  },
  {
    id: 'stf_babangida',
    name: 'Mr. Muhammad Babangida Umar',
    email: 'babangidamuhdumar@gmail.com',
    professional: 'Clinical',
    education: 'Human Anatomy (B.Sc)',
    specialization: 'Advertising and Documentation · Reports to CBPO',
    staffCode: 'ET',
    department: 'BD & Project Delivery',
    role: 'Market Development, Communications & Documentation',
    years: 4,
  },
  {
    id: 'stf_glory',
    name: 'Miss Glory Peter Ayuba',
    email: 'glorianapeter21@gmail.com',
    professional: 'Project Manager',
    education: 'Social Work (B.A)',
    specialization: 'Client management · Reports to CBPO',
    staffCode: 'ET',
    department: 'BD & Project Delivery',
    role: 'Client Manager',
    years: 3,
    phone: '+234 906 873 6996',
    birthday: '05-21',
  },
  {
    id: 'stf_hadiza',
    name: 'Miss Hadiza Muhammed',
    email: 'hadizaabubakar93@yahoo.com',
    professional: 'Data analytics and Visualisation',
    education: 'Business Administration (B.Sc)',
    specialization: 'Data & BI · Reports to CBPO',
    staffCode: 'ET',
    department: 'BD & Project Delivery',
    role: 'Project Manager / Data & BI Analyst',
    years: 1,
    phone: '+234 806 571 6810',
    birthday: '09-04',
  },
  {
    id: 'stf_samson',
    name: 'Mr. Samson Olalere',
    email: 'samsonolalere25@gmail.com',
    professional: 'Project management',
    education: 'Microbiology (B.Sc)',
    specialization: 'Project support · Reports to CBPO',
    staffCode: 'ET',
    department: 'BD & Project Delivery',
    role: 'Project Support Assistant — Radians',
    years: 1,
  },
  {
    id: 'stf_abdulrasheed',
    name: 'Mr. Abdulrasheed Taimiyu',
    email: 'tiyamuabdulrasheed8080@gmail.com',
    professional: 'NSE/ IAENG',
    education: 'Mechanical Engineering (B.Sc)',
    specialization: 'Technical Operations · Reports to Head of Logistics',
    staffCode: 'ET',
    department: 'Logistics & Procurement',
    role: 'Technical Operations & Field Support',
    years: 2,
  },
  {
    id: 'stf_hassana',
    name: 'Miss Hassana Dahiru',
    email: '',
    professional: 'Frontend Website Design & Development',
    education: 'Public Administration (B.Sc)',
    specialization: 'Customer Care Service · Reports to CCSO',
    staffCode: 'ET',
    department: 'Corporate Services',
    role: 'Corporate Services Assistant',
    years: 2,
    phone: '+234 806 155 2197',
    birthday: '01-08',
  },
  {
    id: 'stf_emmanuel',
    name: 'Mr. Emmanuel Chijoke',
    email: 'manuelemeka@gmail.com',
    professional: 'Software Engineer, Machine Learning Engineer, AI Systems Architect',
    education: 'Computer Science (B.Sc)',
    specialization: 'Full-stack software engineering · Reports to MD / CEO',
    staffCode: 'AGM',
    department: 'Technology & Product',
    role: 'CTPO / Lead Engineer & AI Architect',
    years: 6,
  },
  {
    id: 'stf_kelechi',
    name: 'Mr. Kelechi Anyanwu',
    email: 'kayceeanyanwu@gmail.com',
    professional: 'AWS Solutions Architect, Google Data Analytics, ITIL v4, Ethical Hacker',
    education: 'Mathematics & Computer Science',
    specialization: 'VAAS · Reports to CTPO; project line to CBPO',
    staffCode: 'Senior Manager',
    department: 'Technology & Product',
    role: 'System Engineer / Project Lead VAAS',
    years: 7,
  },
  {
    id: 'stf_olakunle',
    name: 'Mr. Olakunle Stephen Oluwadamilola',
    email: 'dammykunle79@gmail.com',
    professional: 'Full-Stack Developer',
    education: 'Hydrology (B.Sc)',
    specialization: 'Web Development and Server Management · Reports to CTPO',
    staffCode: 'Developer 2',
    department: 'Technology & Product',
    role: 'Full-Stack Engineer / Technology Project Manager',
    years: 7,
    phone: '+234 816 476 8989',
    birthday: '01-25',
  },
  {
    id: 'stf_raymond',
    name: 'Mr. Odiaga Raymond',
    email: 'odiagaraymondray@gmail.com',
    education: 'BTech Physics (B.Sc)',
    specialization: 'Backend Development · Reports to CTPO',
    staffCode: 'Full Developer',
    department: 'Technology & Product',
    role: 'Backend Engineer / PCB Project Lead',
    years: 7,
    phone: '+234 907 795 1767',
    birthday: '10-01',
  },
  {
    id: 'stf_gwabare',
    name: 'Mr. Abubakar Abdullahi Gwabare',
    email: 'gwabstech@gmail.com',
    professional: 'Softeware Engineer| FINTECH',
    education: 'Computer Science (HND)',
    specialization: 'TMS & POS · Reports to CTPO',
    staffCode: 'Full Developer',
    department: 'Technology & Product',
    role: 'Product Lead — TMS & POS',
    years: 7,
  },
  {
    id: 'stf_aliyu',
    name: 'Mr. Aliyu Usman',
    email: 'aliyu.usman@blumentechnologies.com',
    education: 'Computer Science (B.Sc)',
    staffCode: 'Full Developer',
    department: 'Technology & Product',
    role: 'Senior Software Engineer / Technical Lead Baggage',
    specialization: 'Reports to CTPO',
    years: 25,
  },
  {
    id: 'stf_muritala',
    name: 'Mr. Ibrahim Muritala',
    email: 'muritalaibrahim097@gmail.com',
    professional: 'Software Engineer',
    education: 'Physics and Electronics (B.Sc)',
    specialization: 'Frontend · Reports to CTPO',
    staffCode: 'Full Developer',
    department: 'Technology & Product',
    role: 'Frontend Software Engineer',
    years: 7,
    phone: '+234 903 597 1227',
    birthday: '02-28',
  },
  {
    id: 'stf_oshoba',
    name: 'Mr. Oluwagbminiyi Oreoluwa Oshoba',
    email: 'gbeminiyi.oshoba@gmail.com',
    professional: 'Advanced Diploma in Software Engineering',
    education: 'Computer Science (Systems Engineering)',
    specialization: 'Developer Operations · Reports to CTPO',
    staffCode: 'Full Developer',
    department: 'Technology & Product',
    role: 'DevOps Engineer',
    years: 10,
    phone: '+234 906 344 5311',
    birthday: '11-07',
  },
  {
    id: 'stf_sherif',
    name: 'Mr. Sherif Adamu',
    email: 'shereefadamu001@gmail.com',
    education: 'Doctor in Veterinary Medicine (DVM)',
    specialization: 'UI UX · Reports to CTPO',
    staffCode: 'Full Developer',
    department: 'Technology & Product',
    role: 'Product Designer / UI-UX Engineer',
    years: 7,
    phone: '+234 903 175 4067',
  },
  {
    id: 'stf_haldar',
    name: 'Mr. Aliyu Hassan (Haldar)',
    email: '',
    staffCode: 'Developer 2',
    department: 'Technology & Product',
    role: 'Embedded Systems Engineer / Hardware Project Lead',
    specialization: 'Reports to CTPO',
  },
  {
    id: 'stf_zarruk',
    name: 'Mr. Abdulsalam Zarruk',
    email: 'abduussalamzarruk@gmail.com',
    professional: 'Frontend Web Developer',
    education: 'Computer Science (Diploma)',
    specialization: 'Frontend Development · Reports to CTPO',
    staffCode: 'Developer 1',
    department: 'Technology & Product',
    role: 'Frontend / Web Developer',
    years: 5,
  },
  {
    id: 'stf_alim',
    name: 'Mr. Alim Habib Dattijo',
    email: 'alimhabibcgartist@gmail.com',
    professional: '3D Artist',
    education: 'Industrial Design (B.Sc)',
    specialization: 'Graphics · Reports to CBPO',
    staffCode: 'Developer 1',
    department: 'BD & Project Delivery',
    role: 'Creative & Motion Graphics Specialist',
    years: 2,
  },
  {
    id: 'stf_babayo',
    name: 'Mr. Abubakar Babayo Abdullahi',
    email: 'babayoaudukhalifa@gmail.com',
    professional: 'Software Engineering',
    education: 'Information Technology (B.Sc)',
    staffCode: 'Executive Trainee',
    department: 'Technology & Product',
    role: 'Frontend Engineer',
    specialization: 'Reports to CTPO',
    years: 10,
    phone: '+234 808 213 1111',
  },
  {
    id: 'stf_liman',
    name: 'Umar Liman',
    email: '',
    department: 'Administration',
    role: 'Office Keeper',
    staffCode: '',
  },
  {
    id: 'stf_yahaya',
    name: 'Mr. Yahaya Iliyasu',
    email: '',
    department: 'Operations',
    role: 'Driver',
    staffCode: '',
    phone: '+234 813 342 6299 / +234 902 353 0088',
    birthday: '01-01',
  },
]

export function seedStaff() {
  return STAFF.map((person, i) => ({
    staffCode: '',
    professional: '',
    education: '',
    specialization: '',
    department: '',
    role: '',
    years: 0,
    phone: '',
    birthday: '',
    color: AVATAR_COLORS[i % AVATAR_COLORS.length],
    ...person,
  }))
}

export function seedEvents() {
  return []
}

export function seedSends() {
  return []
}

export function seedSettings() {
  return {
    ceoName: 'Dr. Yunusa Garba Muhammed',
    ceoTitle: 'CEO/MD',
    ceoEmail: 'ygarbawala@gmail.com',
    replyTo: 'office@blumentechnologies.com',
    ccHr: 'hr@blumentechnologies.com',
    autoSend: true,
    reminder3Day: true,
    weeklySummary: true,
    notifyCeo: true,
    customOccasions: [],
  }
}
