import {
  Award,
  Baby,
  BadgeCheck,
  Cake,
  Car,
  Crown,
  DoorOpen,
  Flower2,
  Gift,
  GraduationCap,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Medal,
  Moon,
  PartyPopper,
  Plane,
  Rocket,
  Sparkles,
  Star,
  Stethoscope,
  Trophy,
  Users,
} from 'lucide-react'

const MAP = {
  welcome: Handshake,
  confirmation: BadgeCheck,
  promotion: Trophy,
  recognition: Medal,
  work_anniversary: PartyPopper,
  project_success: Rocket,
  qualification: Award,
  graduation: GraduationCap,
  farewell: DoorOpen,
  retirement: HeartHandshake,
  birthday: Cake,
  engagement: Sparkles,
  traditional_marriage: Users,
  wedding: Heart,
  wedding_anniversary: HeartHandshake,
  new_baby: Baby,
  naming_ceremony: Baby,
  new_home: Home,
  new_car: Car,
  get_well: Stethoscope,
  illness: HeartPulse,
  bereavement: Flower2,
  eid: Moon,
  christmas: Gift,
  new_year: Star,
  hajj: Plane,
  traditional_title: Crown,
}

export default function OccasionIcon({ type, size = 18 }) {
  const Icon = MAP[type] || Gift
  return <Icon size={size} />
}
